---
- name: Backup EXOS switch primary.cfg and show configuration (Pure Shell)
  hosts: exos_switches
  gather_facts: no
  vars:
    # 1. HOST PATH MAPPING (Must match your docker-compose volumes)
    backup_dir: "/backups/{{ inventory_hostname }}"

  tasks:
    - name: Get current timestamp on localhost
      ansible.builtin.setup:
        filter: ansible_date_time
      delegate_to: localhost
      register: local_facts

    - name: Set timestamp fact
      ansible.builtin.set_fact:
        timestamp: "{{ local_facts.ansible_facts.ansible_date_time.iso8601_basic_short }}"

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0777'
      delegate_to: localhost

    # -----------------------------------------------------------------------
    # TASK 1: SCP THE FILE (Already working)
    # -----------------------------------------------------------------------
    - name: Pull primary.cfg using SCP
      ansible.builtin.shell: >-
        sshpass -e 
        scp 
        -o HostKeyAlgorithms=+ssh-rsa
        -o PubkeyAcceptedKeyTypes=+ssh-rsa
        -o StrictHostKeyChecking=no
        -o UserKnownHostsFile=/dev/null
        admin@{{ ansible_host }}:primary.cfg
        {{ backup_dir }}/primary_{{ timestamp }}.cfg
      environment:
        SSHPASS: "{{ ansible_password }}"
      delegate_to: localhost
      register: scp_result

    - name: Confirm SCP success
      ansible.builtin.debug:
        msg: "primary.cfg saved."
      when: scp_result.rc == 0

    # -----------------------------------------------------------------------
    # TASK 2: SHOW CONFIGURATION (Pipe Method + TTY)
    # -----------------------------------------------------------------------
    - name: Run 'show configuration' via SSH (Pipe Method)
      ansible.builtin.shell: >-
        echo -e "disable clipaging\nshow configuration" | 
        sshpass -e 
        ssh -tt 
        -o HostKeyAlgorithms=+ssh-rsa 
        -o PubkeyAcceptedKeyTypes=+ssh-rsa 
        -o StrictHostKeyChecking=no 
        -o UserKnownHostsFile=/dev/null 
        admin@{{ ansible_host }}
      environment:
        SSHPASS: "{{ ansible_password }}"
      delegate_to: localhost
      register: show_config_raw

    - name: Save 'show configuration' output
      ansible.builtin.copy:
        content: "{{ show_config_raw.stdout }}"
        dest: "{{ backup_dir }}/show_config_{{ timestamp }}.txt"
      delegate_to: localhost

    # -----------------------------------------------------------------------
    # TASK 3: SHOW CONFIGURATION DETAIL
    # -----------------------------------------------------------------------
    - name: Run 'show configuration detail' via SSH (Pipe Method)
      ansible.builtin.shell: >-
        echo -e "disable clipaging\nshow configuration detail" | 
        sshpass -e 
        ssh -tt 
        -o HostKeyAlgorithms=+ssh-rsa 
        -o PubkeyAcceptedKeyTypes=+ssh-rsa 
        -o StrictHostKeyChecking=no 
        -o UserKnownHostsFile=/dev/null 
        admin@{{ ansible_host }}
      environment:
        SSHPASS: "{{ ansible_password }}"
      delegate_to: localhost
      register: show_detail_raw

    - name: Save 'show configuration detail' output
      ansible.builtin.copy:
        content: "{{ show_detail_raw.stdout }}"
        dest: "{{ backup_dir }}/show_config_detail_{{ timestamp }}.txt"
      delegate_to: localhost
