Based on the playbook and log you provided, there are three main issues preventing the backup from working correctly. The most critical one—likely causing the job to hang or fail silently—is related to SSH host key verification in your manual SCP command.

Here is the diagnosis and the corrected playbook.

The Issues

Variable Mismatch (Critical Syntax Error)

Your Code: You register the output of the SCP command to scp_result, but in the debug task immediately following, you try to print scp_manual.

Result: The playbook will crash with an "undefined variable" error when it tries to print the debug message.

SSH Host Key Checking (Hanging)

The Problem: The scp command is running outside of Ansible's connection manager (via delegate_to: localhost). It does not know about the switch's SSH host key.

Result: The command will hang indefinitely asking: "The authenticity of host 'x.x.x.x' can't be established... Are you sure you want to continue connecting (yes/no)?". Since Semaphore is non-interactive, it hangs until it times out.

Fix: You must add -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null to the SCP command options.

File Path Precision

The Problem: While primary.cfg often works, Extreme EXOS can be particular about paths.

Fix: It is safer to use the full path admin@{{ ansible_host }}:/usr/local/cfg/primary.cfg to ensure SCP finds the file.

Corrected Playbook

Here is the fully fixed playbook. Replace your current manual SCP task and Debug task with this updated logic.

code
Yaml
download
content_copy
expand_less
---
- name: Install sshpass if missing (idempotent)
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure sshpass is installed
      ansible.builtin.package:
        name: sshpass
        state: present

- name: Backup EXOS switch primary.cfg via manual SCP and save show configuration
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.network.exos
    backup_dir: "./backups/{{ inventory_hostname }}"

  tasks:
    - name: Get current timestamp on localhost
      ansible.builtin.setup:
        filter: ansible_date_time
      delegate_to: localhost
      register: local_facts

    - name: Set timestamp fact
      ansible.builtin.set_fact:
        timestamp: "{{ local_facts.ansible_facts.ansible_date_time.iso8601_basic_short }}"

    - name: Create local backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Pull primary.cfg using SCP with sshpass (Automated)
      ansible.builtin.command: >-
        sshpass -p '{{ ansible_ssh_password }}' 
        scp -o HostKeyAlgorithms=+ssh-rsa 
        -o PubkeyAcceptedKeyTypes=+ssh-rsa 
        -o StrictHostKeyChecking=no 
        -o UserKnownHostsFile=/dev/null 
        admin@{{ ansible_host }}:/usr/local/cfg/primary.cfg 
        {{ backup_dir }}/primary_{{ timestamp }}.cfg
      delegate_to: localhost
      no_log: true # Keeps password out of logs
      register: scp_result
      # ignore_errors: yes # Uncomment if you want the play to continue even if SCP fails

    - name: Confirm SCP success
      ansible.builtin.debug:
        msg: "primary.cfg successfully backed up!"
      when: scp_result.rc == 0

    - name: Display SCP output (for troubleshooting)
      ansible.builtin.debug:
        msg: 
          - "Return Code: {{ scp_result.rc }}"
          - "StdOut: {{ scp_result.stdout_lines }}"
          - "StdErr: {{ scp_result.stderr_lines }}"
      when: scp_result is defined and scp_result.rc != 0

    - name: Run 'show configuration' and save output
      community.network.exos_command:
        commands: show configuration
      register: show_config

    - name: Save 'show configuration' output to file
      ansible.builtin.copy:
        content: "{{ show_config.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_{{ timestamp }}.txt"
      delegate_to: localhost

    - name: Run 'show configuration detail' and save output
      community.network.exos_command:
        commands: show configuration detail
      register: show_config_detail

    - name: Save 'show configuration detail' output to file
      ansible.builtin.copy:
        content: "{{ show_config_detail.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_detail_{{ timestamp }}.txt"
      delegate_to: localhost
Key Changes Explained

Added SSH Flags: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ensures the command never asks for confirmation, which is essential for automation in Semaphore.

Fixed Variable Name: Changed scp_manual to scp_result in the debug task so it actually prints the output.

Added Path: Changed source to /usr/local/cfg/primary.cfg to be explicit.

Error Handling: The debug task now specifically prints the standard error (stderr_lines) if the return code is not 0, which helps you see exactly why SCP failed (e.g., "Permission denied", "Timeout", etc.).

Google Search Suggestions
Display of Search Suggestions is required when using Grounding with Google Search. Learn more
extreme exos scp primary.cfg path
ansible backup extreme exos switch primary.cfg
