---
- name: Backup EXOS switch primary.cfg via manual SCP and save show configuration
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.network.exos
    backup_dir: "./backups/{{ inventory_hostname }}"

  tasks:
    - name: Get current timestamp on localhost
      ansible.builtin.setup:
        filter: ansible_date_time
      delegate_to: localhost
      register: local_facts

    - name: Set timestamp fact
      ansible.builtin.set_fact:
        timestamp: "{{ local_facts.ansible_facts.ansible_date_time.iso8601_basic_short }}"

    - name: Create local backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
      delegate_to: localhost

    - name: Pull primary.cfg using manual SCP with sshpass (automated password)
      ansible.builtin.command: >-
        sshpass -p '{{ ansible_ssh_password }}'
        scp -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
        admin@{{ ansible_host }}:primary.cfg {{ backup_dir }}/primary_{{ timestamp }}.cfg
      delegate_to: localhost
      environment:
        SSHPASS: '{{ ansible_ssh_password }}'  # Fallback if needed
      register: scp_manual

    - name: Display SCP output (for verification)
      ansible.builtin.debug:
        msg: "{{ scp_manual.stdout_lines + scp_manual.stderr_lines }}"
        
    - name: Run 'show configuration' and save output
      community.network.exos_command:
        commands: show configuration
      register: show_config

    - name: Save 'show configuration' output to file
      ansible.builtin.copy:
        content: "{{ show_config.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_{{ timestamp }}.txt"
      delegate_to: localhost

    - name: Run 'show configuration detail' and save output
      community.network.exos_command:
        commands: show configuration detail
      register: show_config_detail

    - name: Save 'show configuration detail' output to file
      ansible.builtin.copy:
        content: "{{ show_config_detail.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_detail_{{ timestamp }}.txt"
      delegate_to: localhost
