---
- name: Backup EXOS switch primary.cfg via SCP and save show configuration
  hosts: exos_switches
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.network.exos
    backup_dir: "./backups/{{ inventory_hostname }}"

  tasks:
    - name: Get current timestamp on localhost
      ansible.builtin.setup:
        filter: ansible_date_time
      delegate_to: localhost
      run_once: false
      register: local_facts

    - name: Set timestamp fact
      ansible.builtin.set_fact:
        timestamp: "{{ local_facts.ansible_facts.ansible_date_time.iso8601_basic_short }}"

    - name: Verify connectivity - Run 'show switch' command
      community.network.exos_command:
        commands: show switch
      register: show_switch_output

    - name: Display 'show switch' output (confirms login and basic command execution)
      ansible.builtin.debug:
        msg: "{{ show_switch_output.stdout_lines }}"

    - name: Verify filesystem - Run 'ls' command (should list primary.cfg if in correct dir)
      community.network.exos_command:
        commands: ls
      register: ls_output

    - name: Display 'ls' output (look for primary.cfg)
      ansible.builtin.debug:
        msg: "{{ ls_output.stdout_lines }}"

    - name: Verify current directory - Run 'pwd' command
      community.network.exos_command:
        commands: pwd
      register: pwd_output

    - name: Display current working directory
      ansible.builtin.debug:
        msg: "{{ pwd_output.stdout[0] }}"
        
    - name: Create local backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
      delegate_to: localhost

    - name: Copy primary.cfg from switch via SCP using relative filename
      ansible.builtin.fetch:
        src: primary.cfg
        dest: "{{ backup_dir }}/primary_{{ timestamp }}.cfg"
        flat: yes
      delegate_to: localhost

    - name: Run 'show configuration' and save output
      community.network.exos_command:
        commands: show configuration
      register: show_config

    - name: Save 'show configuration' output to file
      ansible.builtin.copy:
        content: "{{ show_config.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_{{ timestamp }}.txt"
      delegate_to: localhost

    - name: Run 'show configuration detail' (more complete)
      community.network.exos_command:
        commands: show configuration detail
      register: show_config_detail

    - name: Save 'show configuration detail' output to file
      ansible.builtin.copy:
        content: "{{ show_config_detail.stdout[0] }}"
        dest: "{{ backup_dir }}/show_config_detail_{{ timestamp }}.txt"
      delegate_to: localhost

    - name: Debug - List files in current directory on switch
      community.network.exos_command:
        commands: ls
      register: ls_output

    - name: Display ls output
      ansible.builtin.debug:
        msg: "{{ ls_output.stdout_lines }}"
