---
- name: Deploy EXOS Banners
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    # It is best practice to store passwords in Semaphore Secrets, not plain text
    ansible_password: "" 
    ansible_network_os: community.network.exos
    
  tasks:
    - name: Configure Before-Login Banner
      community.network.exos_banner:
        banner: before-login
        text: |
          ***********************************************************************
          *                                                                     *
          *  WARNING: UNAUTHORIZED ACCESS IS PROHIBITED                         *
          *                                                                     *
          *  This system is property of Capstone Labs. All activity is          *
          *  monitored and logged. Unauthorized use is a violation of federal   *
          *  and state laws (18 USC 1030, etc.) and may result in criminal      *
          *  prosecution.                                                       *
          *                                                                     *
          *  By continuing, you acknowledge acceptance of our Acceptable Use    *
          *  Policy and consent to monitoring.                                  *
          *                                                                     *
          *  https://capstonelabs.net/security-policy                           *
          *                                                                     *
          ***********************************************************************
        state: present

    - name: Configure After-Login Banner
      community.network.exos_banner:
        banner: after-login
        text: |
          ╔══════════════════════════════════════════════════════════════════════╗
          ║                 CAPSTONE LABS CORE SWITCH - CORE-02                  ║
          ╠══════════════════════════════════════════════════════════════════════╣
          ║  Unauthorized changes are strictly prohibited.                       ║
          ║  All configuration changes must be approved and documented.          ║
          ║  This device is actively monitored. Save your work!                  ║
          ╚══════════════════════════════════════════════════════════════════════╝
        state: present

    - name: Save configuration
      community.network.exos_config:
        save: yes
